version: '3'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./blog/:/var/www/blog/
        networks:
            - app
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./blog/:/var/www/blog/
        ports:
            - 8001:80
        networks:
            - app
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
          MYSQL_DATABASE: 
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: localhost 
        ports:
          - "6033:3306"
        volumes:
          - dbdata:/var/lib/mysql
        networks:
            - app
            
volumes:
    dbdata:
networks:
    app: