version: '3'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./blog/:/var/www/blog/
        networks:
            - blog
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./blog/:/var/www/blog/
        ports:
            - 8001:80
        networks:
            - blog
networks:
    blog: