version: '3'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./root/:/var/www/
        networks:
            - app
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./root/:/var/www/
        ports:
            - 8001:80
        networks:
            - app
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST} 
        ports:
          - "${MYSQL_PORT}:3306"
        volumes:
          - ./docker/mysql/data:/docker-entrypoint-initdb.d
        networks:
            - app
            
networks:
    app: