<?php use Blog\Session as Session; ?>
<!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
	<form name="entry" method="post" action="<?php echo $this->getFormField('url'); ?>">
		<table>
                        <tr>
                            <td colspan="2"><?php echo $this->title; ?> an entry:</td>
                        </tr>
			<tr>
				<td>
                                   Title *
                                    <br/>
                                    <b><?php if($this->hasError('title')) echo $this->getError('title'); ?></b>
                                </td>
				<td><input type="input" name="title" value="<?php echo $this->getFormField('title'); ?>"/></td>
			</tr>
			<tr>
				<td>
                                    Text *
                                    <br/>
                                    <b><?php if($this->hasError('text')) echo $this->getError('text'); ?></b>
                                </td>
				<td><textarea name="text"><?php echo $this->getFormField('text'); ?></textarea></td>
			</tr>
			<tr>
				<td colspan="2"><input type="submit" name="senden" /></td>
			</tr>
		</table>
		<input type="hidden" name="action" value="<?php echo $this->getFormField('action'); ?>"/>
		<input type="hidden" name="author" value="<?php echo Session::getInstance()->get('author_id'); ?>"/>
	</form>
</div>
            </div>
	</div>
</main>
