<!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
	<form name="contact" method="post" action="">
		<table>
                        <tr>
                            <td>Authors: *
					<b><?php if($this->hasError('author')) echo $this->getError('author'); ?></b></td>
					<td>
                        		<select name="author">
                        			  <option value="" selected>choose author</option>
<?php foreach ($this->authors as $key => $value): ?>


  <option value="<?php echo $value->id; ?>"><?php echo $value->fullname; ?></option>


<?php endforeach ?>
</select>
</td>
</tr>	
			<tr>
				<td>Your email: *</td>
				<td><input type="input" name="email" value="<?php echo $this->getFormField('email'); ?>"/>
					<br/>
					<b><?php if($this->hasError('email')) echo $this->getError('email'); ?></b>
				</td>
			</tr>
			<tr>
				<td>
                                     Message: *
                                    <br/>
                                    <b><?php if($this->hasError('message')) echo $this->getError('message'); ?></b>
                                </td>
				<td><textarea name="message"><?php echo $this->getFormField('message'); ?></textarea></td>
			</tr>
			<tr>
				<td colspan="2"><input type="submit" name="senden" /></td>
			</tr>
		</table>
		<input type="hidden" name="action" value="contact"/>
	</form>
</div>
				</div>
			</div>
        </main>
