<?php use Blog\Session as Session; ?>
<div>
	<table>
<?php foreach ($this->entries as $key => $value): ?>
<tr>
	<td><a href="<?php echo $this->getUrl('index', 'detail', $value->title); ?>"><?php echo $value->title; ?></a></td>
	<td><?php echo date('d.m.Y H:i', $value->published_date); ?></td>
</tr>
<tr>	
	<td colspan="2"><?php echo $value->text; ?></td>
</tr>	
<tr>
	<td><a href="<?php echo $this->getUrl('index', 'author', $value->fullname); ?>"><?php echo $value->fullname; ?></a></td>
	<td>Anzahl Kommentare: <?php echo $value->comment_count; ?></td>
</tr>
<?php if(Session::getInstance()->isLoggedIn() && $value->author_id === Session::getInstance()->get('author_id')){ ?>
<tr>
	<td><a href="<?php echo $this->getUrl('blog', 'edit', $value->id); ?>">Edit</a></td>
	<td><a href="<?php echo $this->getUrl('blog', 'delete', $value->id); ?>">delete</a></td>
</tr>
<?php } ?>
<?php endforeach ?>
	</table>
</div>
<?php if (!empty($this->entry)) { ?>
<br/>
<?php
	$this->renderPartial('comment.phtml', ['comments' => $this->comments, 'entry' => $this->entry, 'formToken' => uniqid('f')]); 
} ?>
