<?php use Blog\Session as Session; ?>
		<div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
				<?php foreach ($this->entries as $key => $value): ?>
					<div class="post-preview">
							<a href="<?php echo $this->getUrl('index', 'detail', $value->title); ?>">
								<h2 class="post-title"><?php echo $value->title; ?></h2>
							</a>
							<?php if (empty($this->entry)) { ?>
							<h5 class="post-subtitle"><?php echo substr($value->text, 0, 50); ?>...</h5>
							<?php } else { ?>
                            <h5 class="post-subtitle"><?php echo $value->text; ?></h5>
							<?php } ?>
                        <p class="post-meta">
							Anzahl Kommentare: <?php echo $value->comment_count; ?><br/>
                            Posted by
                            <a href="<?php echo $this->getUrl('index', 'author', $value->fullname); ?>"><?php echo $value->fullname; ?></a>
                            on <?php echo date('d.m.Y H:i', $value->published_date); ?>
							<br/>
							<?php if(Session::getInstance()->isLoggedIn() && $value->author_id === Session::getInstance()->get('author_id')){ ?>
								<a href="<?php echo $this->getUrl('blog', 'edit', $value->id); ?>">Edit</a>
								 - 
								<a href="<?php echo $this->getUrl('blog', 'delete', $value->id); ?>">Delete</a>
							<?php } ?>
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
				<?php endforeach ?>                    
                </div>
            </div>
        </div>
<?php if (!empty($this->entry)) { ?>
<br/>
<?php
	$this->renderPartial('comment.phtml', ['comments' => $this->comments, 'entry' => $this->entry, 'formToken' => uniqid('f')]); 
} ?>
