<!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
						<form name="login" method="post" action="<?php echo $this->getUrl('index', 'login'); ?>">
						<p>Email:<br/><input type="email" name="email" value="<?php echo $this->getFormField('email'); ?>"/></p>
						<p>Password:<br/><input type="password" name="password" value=""/></p>
						<input type="submit" name="senden" />
						</form>
					</div>
				</div>
			</div>
        </main>